# Issue Solution: Determining the number of shells

In [18]:
from dmriprep.utils.vectors import DiffusionGradientTable

import numpy as np

In [19]:
dwi = "../../data/sub-03_dwi.nii.gz"
bvec = "../../data/sub-03_dwi.bvec"
bval = "../../data/sub-03_dwi.bval"

In [20]:
np.genfromtxt(bval)

array([   5.,    5.,  610., 1240.,  615., 1225.,  625., 1230.,  620.,
       1230.,  610., 1240.,  615., 1225.,  620., 1220.,  620.,    5.,
       1225.,  615., 1240.,  625., 1230.,  620., 1240.,  615., 1225.,
        615., 1230.,  625., 1230.,  610., 1230.,    5.,  615., 1235.,
        615., 1220.,  625., 1245.,  620., 1240.,  620., 1225.,  615.,
       1235.,  620., 1225.,  605.,    5., 1225.,  625., 1235.,  615.,
       1230.,  620., 1230.,  610., 1235.,  620., 1230.,  620., 1220.,
        625., 1235.,    5.,  610., 1230.,  620., 1240.,  615., 1230.,
        625., 1230.,  610., 1235.,  610., 1240.,  620., 1235.,  620.,
          5., 1220.,  615., 1230.,  615., 1230.,  620., 1240.,  610.,
       1215.,  620., 1240.,  620., 1225.,  620., 1225.,  615., 1230.,
          5.,  890., 1800.,  895., 1785.,  910., 1790.,  900., 1795.,
        890., 1800.,  895., 1785.,  905., 1780.,  900.,    5., 1785.,
        895., 1805.,  905., 1795.,  900., 1800.,  895., 1780.,  895.,
       1790.,  905.,

In [21]:
gtab = DiffusionGradientTable(dwi_file=dwi, bvecs=bvec, bvals=bval)

gtab._bvals

Inconsistent bvals and bvecs (13, 0 low-b, respectively).


array([   0,    0,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600,
       1200,  600, 1200,  600, 1200,  600,    0, 1200,  600, 1200,  600,
       1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,
          0,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,
        600, 1200,  600, 1200,  600,    0, 1200,  600, 1200,  600, 1200,
        600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,    0,
        600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600,
       1200,  600, 1200,  600,    0, 1200,  600, 1200,  600, 1200,  600,
       1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,
          0,  900, 1800,  900, 1800,  900, 1800,  900, 1800,  900, 1800,
        900, 1800,  900, 1800,  900,    0, 1800,  900, 1800,  900, 1800,
        900, 1800,  900, 1800,  900, 1800,  900, 1800,  900, 1800,    0,
        900, 1800,  900, 1800,  900, 1800,  900, 1800,  900, 1800,  900,
       1800,  900, 1800,  900,    0, 1800,  900, 18

In [22]:
gtab.bvals

array([   0,    0,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600,
       1200,  600, 1200,  600, 1200,  600,    0, 1200,  600, 1200,  600,
       1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,
          0,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,
        600, 1200,  600, 1200,  600,    0, 1200,  600, 1200,  600, 1200,
        600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,    0,
        600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600,
       1200,  600, 1200,  600,    0, 1200,  600, 1200,  600, 1200,  600,
       1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,  600, 1200,
          0,  900, 1800,  900, 1800,  900, 1800,  900, 1800,  900, 1800,
        900, 1800,  900, 1800,  900,    0, 1800,  900, 1800,  900, 1800,
        900, 1800,  900, 1800,  900, 1800,  900, 1800,  900, 1800,    0,
        900, 1800,  900, 1800,  900, 1800,  900, 1800,  900, 1800,  900,
       1800,  900, 1800,  900,    0, 1800,  900, 18

In [23]:
from dipy.core.gradients import unique_bvals

In [24]:
unique_bvals(gtab._bvals)

array([   0.,  600.,  900., 1200., 1800.])

In [25]:
from collections import Counter

In [31]:
Counter(sorted(gtab._bvals))

Counter({0: 13, 600: 46, 900: 46, 1200: 46, 1800: 46})